### PR TITLE
DR-2572 Linting and formatting

### PR DESCRIPTION
**Pull request by 7emansell**
## Ticket:
Fixes JIRA ticket [DR-2572](https://jira.nypl.org/browse/DR-2572).

## This PR does the following:
- Adds `husky`
- Adds `lint-staged`
- Adds `eslint `(Next.js config, which includes `react-hooks` and `jsx-a11y`)
- Adds `prettier` (basic config modeled off DS repo)
- Sets `eslint` and `prettier` to run on commit

## How has this been tested?
Locally.

## Accessibility concerns or updates

N/A.
### Checklist:

- [x] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by 7emansell** [comment]
Branched off swim lanes so there's some weirdness, might wait until I merge swim lanes in to merge this in

**Review by EdwinGuzman — COMMENTED** [review]
This looks good. I did not review the json API route related code because that's still being worked on separately.

Should this PR point to the json data branch to see just the new changes? If so, are you okay with waiting until that PR is merged before this is merged?

Out of curiosity, how did you lint all the files in the repo? Was it through running `npm lint`?

**Comment by 7emansell** [comment]
> Should this PR point to the json data branch to see just the new changes? If so, are you okay with waiting until that PR is merged before this is merged?

Yes, sounds good.

> Out of curiosity, how did you lint all the files in the repo? Was it through running `npm lint`?

`npm run lint`
Which then runs `next lint`.

**Comment by EdwinGuzman** [comment]
Accessibility linter works well! (I'm ignoring the nextjs specific lint message, we don't need to worry about that).

Screen Shot 2023-10-19 at 1 42 26 PM

**Review by EdwinGuzman — APPROVED** [review]

**Review by avertrees — APPROVED** [review]

**Pull request merged**
